# Generated by Django 3.2.6 on 2023-06-10 03:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localización')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('incidence_type', models.CharField(choices=[('accidente_aereo', 'Accidente aéreo'), ('accidente_transito', 'Accidente de tránsito'), ('colapso_puente', 'Alerta por colapso de puente'), ('arbol_caido', 'Árbo caído'), ('asfixia_inmersion', 'Asfixia por inmersión'), ('aumento_cauce', 'Aumento de cauce'), ('aumento_caudal', 'Aumento  de caudal')], default='tipo1', max_length=50, verbose_name='Tipo incidente')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('finalizado', 'Finalizado')], default='creado', max_length=50, verbose_name='Status')),
                ('image1', models.FileField(upload_to='incidencia_fotos', verbose_name='Foto 1')),
                ('image2', models.FileField(upload_to='incidencia_fotos', verbose_name='Foto 2')),
                ('image3', models.FileField(upload_to='incidencia_fotos', verbose_name='Foto 3')),
                ('audio', models.FileField(upload_to='incidencia_audioa', verbose_name='Audio')),
                ('video', models.FileField(upload_to='incidencia_video', verbose_name='Video')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'sini_incidence',
                'managed': True,
            },
        ),
    ]
