# Generated by Django 3.2.6 on 2023-06-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='image1',
            field=models.ImageField(upload_to='incidencia_fotos', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image2',
            field=models.ImageField(upload_to='incidencia_fotos', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image3',
            field=models.ImageField(upload_to='incidencia_fotos', verbose_name='Foto 3'),
        ),
    ]
