# Generated by Django 3.2.6 on 2023-05-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='audio',
            field=models.FileField(default=0, upload_to='incidencia_audioa', verbose_name='Audio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='foto1',
            field=models.FileField(default=0, upload_to='incidencia_fotos', verbose_name='Foto 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='foto2',
            field=models.FileField(default=0, upload_to='incidencia_fotos', verbose_name='Foto 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='foto3',
            field=models.FileField(default=0, upload_to='incidencia_fotos', verbose_name='Foto 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='video',
            field=models.FileField(default=0, upload_to='incidencia_video', verbose_name='Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_incidente',
            field=models.CharField(choices=[('accidente_aereo', 'Accidente aéreo'), ('accidente_transito', 'Accidente de tránsito'), ('colapso_puente', 'Alerta por colapso de puente'), ('arbol_caido', 'Árbo caído'), ('asfixia_inmersion', 'Asfixia por inmersión'), ('aumento_cauce', 'Aumento de cauce'), ('aumento_caudal', 'Aumento  de caudal')], default='tipo1', max_length=50, verbose_name='Tipo incidente'),
        ),
    ]
