# Generated by Django 3.2.6 on 2023-07-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo?'),
        ),
    ]
