# Generated by Django 3.2.6 on 2023-06-13 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sini', '0002_auto_20230610_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre grupo')),
            ],
            options={
                'verbose_name': 'Grupos API',
                'verbose_name_plural': 'Grupos API',
                'db_table': 'sini_api_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Token')),
                ('blacklisted_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Token',
                'db_table': 'sini_api_blacklisted_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre y apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('token_fcm', models.CharField(max_length=254, verbose_name='Token')),
                ('password', models.CharField(blank=True, default='usuario', max_length=250, null=True)),
                ('password_str', models.CharField(blank=True, max_length=50, null=True, verbose_name='Password STR')),
                ('active', models.BooleanField(default=False, verbose_name='Activo?')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='sini.apigroup', verbose_name='Grupo')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Usuario API',
                'verbose_name_plural': 'Usuarios API',
                'db_table': 'sini_api_user',
                'managed': True,
            },
        ),
    ]
