# Generated by Django 3.2.6 on 2023-07-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0002_alter_incidence_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
    ]
