# Generated by Django 3.2.6 on 2023-07-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0003_alter_incidence_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidence',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AlterModelOptions(
            name='mobilewarning',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
    ]
