# Generated by Django 3.2.6 on 2023-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0003_apigroup_apiuser_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='token_fcm',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Token'),
        ),
    ]
