# Generated by Django 3.2.6 on 2023-06-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0004_alter_apiuser_token_fcm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='apiuser',
            table=None,
        ),
    ]
