# Generated by Django 3.2.6 on 2023-07-26 22:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0006_auto_20230726_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True, 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Localización'),
        ),
    ]
