# Generated by Django 3.2.6 on 2023-07-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0007_auto_20230726_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='api_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sini.apigroup', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='api_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sini.apiuser', verbose_name='Usuario'),
        ),
    ]
