# Generated by Django 3.2.6 on 2023-06-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0007_mobilewarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AddField(
            model_name='mobilewarning',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
    ]
