# Generated by Django 3.2.6 on 2023-07-31 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sini', '0013_alter_notification_status_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('decription', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'arbolsaf_contact',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
