# Generated by Django 3.2.6 on 2023-07-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0014_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decription',
            new_name='description',
        ),
    ]
