# Generated by Django 3.2.6 on 2023-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0018_auto_20230803_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencetype',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Tipo Incidencia', 'verbose_name_plural': 'Tipos Incidencia'},
        ),
        migrations.AddField(
            model_name='incidence',
            name='type_incidence_str',
            field=models.CharField(default='vacio', editable=False, max_length=255, verbose_name='Tipo incidente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilewarning',
            name='type_incidence_str',
            field=models.CharField(default='vacio', editable=False, max_length=255, verbose_name='Tipo incidente'),
            preserve_default=False,
        ),
    ]
