# Generated by Django 3.2.6 on 2023-09-01 14:40

from django.db import migrations, models
import sini.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0019_auto_20230803_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='incidencia_audioa', validators=[sini.validators.validate_audio_file_extension], verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='incidencia_fotos', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='incidencia_fotos', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='incidencia_fotos', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='incidencia_video', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='mobilewarning',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='aviso_audios', validators=[sini.validators.validate_audio_file_extension], verbose_name='Audio'),
        ),
    ]
