# Generated by Django 3.2.6 on 2024-05-31 06:43

from django.db import migrations, models
import django.db.models.deletion
import sini.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0011_fcmdevice_fcm_django_registration_id_user_id_idx'),
        ('sini', '0019_auto_20230803_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='device',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Es anónimo?'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='incidencia_audioa', validators=[sini.validators.validate_audio_file_extension], verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='incidencia_fotos', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='incidencia_fotos', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='incidencia_fotos', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='incidencia_video', validators=[sini.validators.validate_video_file_extension], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='mobilewarning',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='aviso_audios', validators=[sini.validators.validate_audio_file_extension], verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='mobilewarning',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='aviso_video', validators=[sini.validators.validate_video_file_extension], verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_user', to='fcm_django.fcmdevice', verbose_name='Dispositivo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_user', to='sini.apiuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'db_table': 'sini_user_device',
                'managed': True,
            },
        ),
    ]
