# Generated by Django 3.2.6 on 2024-05-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0011_fcmdevice_fcm_django_registration_id_user_id_idx'),
        ('sini', '0021_auto_20240531_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to='fcm_django.fcmdevice', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to='sini.apiuser', verbose_name='Usuario'),
        ),
    ]
