# Generated by Django 3.2.6 on 2024-06-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0022_auto_20240531_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiniFCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='Identificador del dispositivo', max_length=255, null=True, verbose_name='Device ID')),
                ('registration_id', models.TextField(unique=True, verbose_name='Token FCM')),
                ('type', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], max_length=10)),
                ('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to='sini.apiuser')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivo',
                'db_table': 'sini_fcm_device',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='contact',
            table='sini_contact',
        ),
        migrations.AlterModelTable(
            name='incidencetype',
            table='sini_type_incidence',
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
