# Generated by Django 3.2.6 on 2024-06-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sini', '0023_auto_20240605_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinifcmdevice',
            name='name',
            field=models.CharField(default='nombre', max_length=255, verbose_name='Nombre dispositivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sinifcmdevice',
            name='active',
            field=models.BooleanField(default=True, help_text='Los dispositivos inactivos no recibiran notificaciones', verbose_name='Is active'),
        ),
    ]
